# Uncomment the next line to define a global platform for your project
 platform :ios, '17.0'

target 'Shopify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopify
pod 'Alamofire', '~> 5.8.0'
pod 'ReachabilitySwift'
pod 'Kingfisher'
pod 'lottie-ios'


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end

  target 'ShopifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopifyUITests' do
    # Pods for testing
  end

end
